import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Nike Slim shirts",
      category: "shirts",
      image: "/images/p1.jpg",
      countInStock: 10,
      price: 120,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas fit shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 5,
      brand: "Adidas",
      rating: 5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 150,
      countInStock: 5,
      brand: "Nike",
      rating: 4.8,
      numReviews: 9,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "pants",
      category: "shirts",
      image: "/images/p4.jpg",
      price: 150,
      brand: "Nike",
      countInStock: 3,
      rating: 4.9,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "puma slim pants",
      category: "pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas fit pant",
      category: "pants",
      image: "/images/p6.jpg",
      price: 139,
      brand: "Adidas",
      countInStock: 2,
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
